/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic_tac_toe;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author Syed Huzaifa
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
  int temp1=0;
  int temp2=0;
  
    public Start() {
        initComponents();
         player_1_s.setText( first.str1);
         player_2_s.setText( first.str2);
         player_1_sign_s.setText( first.sign1);
         player_2_sign_s.setText( first.sign2);
        this.setLocationRelativeTo(null);
    }
/*static int toss()
{
    Random r=new Random();
    int min=1;
    int max=2;
    int ran=0;
    int range=max-min;
    for(int a=0;a<1;a++)
    {
        ran= r.nextInt((range+1))+min;
    }
    return ran;
}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      String but_1,but_2,but_3,but_4,but_5,but_6,but_7,but_8,but_9;
  
    void play()
    {
    
    if(but_1=="X"&&but_2=="X"&&but_3=="X")
      {
          if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");  

      }
    else if(but_1=="X"&&but_4=="X"&&but_7=="X")
      {   
            if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
       
      }
    else if(but_7=="X"&&but_5=="X"&&but_3=="X")
      {   
            if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
      
      }
    else if(but_1=="X"&&but_5=="X"&&but_9=="X")
          {
                if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
              
          }
          
    else if(but_3=="X"&&but_6=="X"&&but_9=="X")
       {
          if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
           
       }
    else if(but_7=="X"&&but_8=="X"&&but_9=="X")
           {       
                 if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
              
           }
    else if(but_4=="X"&&but_5=="X"&&but_6=="X")
           {       
              if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
              
           }
    else if(but_2=="X"&&but_5=="X"&&but_8=="X")
           {       
                if( first.sign1=="X")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="X")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
               
           }
           
    else if(but_1=="O"&&but_2=="O"&&but_3=="O")
           {
                 if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
              
           }
      
    else if(but_7=="O"&&but_5=="O"&&but_3=="O")
      {  
         
              if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
      
      }
    else if(but_4=="O"&&but_5=="O"&&but_6=="O")
           {       
                  if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
            
           }
    else if(but_1=="O"&&but_4=="O"&&but_7=="O")
      {
            if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
          
       
      }
    else if(but_1=="O"&&but_5=="O"&&but_9=="O")
          {
                if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
           
          }
    else if(but_3=="O"&&but_6=="O"&&but_9=="O")
                  {
                       if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
                   
                  }
    else if(but_7=="O"&&but_8=="O"&&but_9=="O")  
           { 
                if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
               
           }
    else if(but_2=="O"&&but_5=="O"&&but_8=="O")
           {       
               if( first.sign1=="O")
      JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str1+" You Wins");
          if( first.sign2=="O")
             JOptionPane.showMessageDialog(null, "Congrats!!! "+first.str2+" You Wins");
              
           }
    //else if(but_1!=but_9&&but_1!=but_7&&but_1!=but_3&&but_2!=but_8&&but_3!=but_7&&but_3!=but_9&&but_4!=but_6)
          //JOptionPane.showMessageDialog(null,"No One Wins.....");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_1 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        player_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        player_1_s = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        player_2_s = new javax.swing.JLabel();
        player_1_sign_s = new javax.swing.JLabel();
        player_2_sign_s = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jPanel1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        bt_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_1MouseReleased(evt);
            }
        });
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_3MouseReleased(evt);
            }
        });

        bt_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_2MouseReleased(evt);
            }
        });
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_4MouseReleased(evt);
            }
        });
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_5MouseReleased(evt);
            }
        });

        bt_6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_6MouseReleased(evt);
            }
        });

        bt_7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_7MouseReleased(evt);
            }
        });

        bt_8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_8MouseReleased(evt);
            }
        });

        bt_9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_9MouseReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        player_panel.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Player 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign");

        player_1_sign_s.setText("jLabel5");

        player_2_sign_s.setText("jLabel6");

        javax.swing.GroupLayout player_panelLayout = new javax.swing.GroupLayout(player_panel);
        player_panel.setLayout(player_panelLayout);
        player_panelLayout.setHorizontalGroup(
            player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player_panelLayout.createSequentialGroup()
                .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(player_panelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(player_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player_1_s, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(player_2_sign_s, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(player_1_sign_s, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player_2_s, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        player_panelLayout.setVerticalGroup(
            player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(player_1_s, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(player_1_sign_s))
                .addGap(16, 16, 16)
                .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(player_2_s, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(player_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(player_2_sign_s))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("New Game");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(bt_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(bt_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(bt_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(player_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(player_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_1MouseReleased
        // TODO add your handling code here:

        if(temp2!=0)
        temp1=0;
        else
        temp1++;

    }//GEN-LAST:event_bt_1MouseReleased

     
    private void bt_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_1MousePressed
        // TODO add your handling code here:
        if(temp1==0)
        {
            bt_1.setText("X");
            but_1=bt_1.getText();
            bt_1.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_1.setText("O");
             but_1=bt_1.getText();
            bt_1.setForeground(Color.blue);
            temp2++;
        }
        play();
    }//GEN-LAST:event_bt_1MousePressed
 
   
    private void bt_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_bt_1MouseExited

    private void bt_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bt_1MouseClicked

    private void bt_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_2MousePressed
        // TODO add your handling code here:
            if(temp1==0)
        {
            bt_2.setText("X");
              but_2=bt_2.getText();
            bt_2.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_2.setText("O");
              but_2=bt_2.getText();
            bt_2.setForeground(Color.blue);
            temp2++;
        }
            play();
    }//GEN-LAST:event_bt_2MousePressed

    private void bt_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_2MouseReleased
        // TODO add your handling code here:
       if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_2MouseReleased

    private void bt_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_2MouseClicked

    private void bt_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_2MouseExited

    private void bt_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_3MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_3.setText("X");
              but_3=bt_3.getText();
            bt_3.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_3.setText("O");
              but_3=bt_3.getText();
            bt_3.setForeground(Color.blue);
            temp2++;
        }
         play();
    }//GEN-LAST:event_bt_3MousePressed

    private void bt_3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_3MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_3MouseReleased

    private void bt_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_4MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_4.setText("X");
             but_4=bt_4.getText();
            bt_4.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_4.setText("O");
             but_4=bt_4.getText();
            bt_4.setForeground(Color.blue);
            temp2++;
        }
        play();
    }//GEN-LAST:event_bt_4MousePressed

    private void bt_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_4MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_4MouseReleased

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_5MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_5.setText("X");
             but_5=bt_5.getText();
            bt_5.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_5.setText("O");
             but_5=bt_5.getText();
            bt_5.setForeground(Color.blue);
            temp2++;
        }
         play();
    }//GEN-LAST:event_bt_5MousePressed

    private void bt_5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_5MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_5MouseReleased

    private void bt_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_6MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_6.setText("X");
             but_6=bt_6.getText();
            bt_6.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_6.setText("O");
             but_6=bt_6.getText();
            bt_6.setForeground(Color.blue);
            temp2++;
        }
         play();
    }//GEN-LAST:event_bt_6MousePressed

    private void bt_6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_6MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_6MouseReleased

    private void bt_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_7MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_7.setText("X");
             but_7=bt_7.getText();
            bt_7.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_7.setText("O");
             but_7=bt_7.getText();
            bt_7.setForeground(Color.blue);
            temp2++;
        }
         play();
    }//GEN-LAST:event_bt_7MousePressed

    private void bt_7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_7MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_7MouseReleased

    private void bt_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_8MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_8.setText("X");
             but_8=bt_8.getText();
            bt_8.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_8.setText("O");
             but_8=bt_8.getText();
            bt_8.setForeground(Color.blue);
            temp2++;
        }
         play();
    }//GEN-LAST:event_bt_8MousePressed

    private void bt_8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_8MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_8MouseReleased

    private void bt_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_9MousePressed
        // TODO add your handling code here:
         if(temp1==0)
        {
            bt_9.setText("X");
             but_9=bt_9.getText();
            bt_9.setForeground(Color.red);
            temp2=0;
        }

        else
        {
            bt_9.setText("O");
             but_9=bt_9.getText();
            bt_9.setForeground(Color.blue);
            temp2++;
        }
         play();
    }//GEN-LAST:event_bt_9MousePressed

    private void bt_9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_9MouseReleased
        // TODO add your handling code here:
           if(temp2!=0)
        temp1=0;
        else
        temp1++; 
    }//GEN-LAST:event_bt_9MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        temp1=0;
        temp2=0;
        but_1=null;
        but_2=null;
        but_3=null;
        but_4=null;
        but_5=null;
        but_6=null;
        but_7=null;
        but_8=null;
        but_9=null;
        
        bt_1.setText(null);
        bt_2.setText(null);
        bt_3.setText(null);
        bt_4.setText(null);
        bt_5.setText(null);
        bt_6.setText(null);
        bt_7.setText(null);
        bt_8.setText(null);
        bt_9.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new first().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel1CaretPositionChanged
    }//GEN-LAST:event_jPanel1CaretPositionChanged

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // System.out.println(toss());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel player_1_s;
    private javax.swing.JLabel player_1_sign_s;
    public javax.swing.JLabel player_2_s;
    private javax.swing.JLabel player_2_sign_s;
    public javax.swing.JPanel player_panel;
    // End of variables declaration//GEN-END:variables
}
